apiVersion: thinkube.io/v1
kind: ThinkubeDeployment
metadata:
  name: "{{ project_name }}"

spec:
  containers:
    - name: diffusion
      build: .
      port: 7860
      size: xlarge
      gpu:
        count: 1
        memory: "20Gi"  # SDXL needs ~20GB GPU memory
      health: /health
      test:
        enabled: false  # Testing image generation requires GPU, skip in CI/CD
  
  # Routing configuration
  routes:
    - path: /
      to: diffusion